services:
  - type: web
    name: myauthserver
    runtime: docker
    dockerfilePath: ./Dockerfile
    port: 9000
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: myauthserver-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: myauthserver-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: myauthserver-db
          property: password
